services:
  openclaw-gateway:
    build: 
      context: .
      args:
        OPENCLAW_INSTALL_BROWSER: "1"
        OPENCLAW_DOCKER_APT_PACKAGES: ${OPENCLAW_DOCKER_APT_PACKAGES}
    pull_policy: build
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND}",
        "--port",
        "${OPENCLAW_GATEWAY_PORT}",
        "--allow-unconfigured",
      ]

  openclaw-cli:
    build: 
      context: .
      args:
        OPENCLAW_INSTALL_BROWSER: "1"
        OPENCLAW_DOCKER_APT_PACKAGES: ${OPENCLAW_DOCKER_APT_PACKAGES}
    pull_policy: build
